Prototype jujin
Porkstewdio/pork_your_markdown pull request #3
Opened 2018-05-16 18:07 UTC by ciiwol

npm init (package.json 생성)
rollup 기본 세팅 (rollup.config.js)
모듈 만듬 (pumd.js를 main.js와 getMarkdown.js로 분리)

2018-05-17 02:57 UTC, eastroots92 requested changes

2018-05-17 02:57 UTC, eastroots92 commented on examples/sample.html
> +            url=" https://raw.githubusercontent.com/Porkstewdio/pork_your_markdown/master/README.md"></div>
URL 같은 경우에는 https://raw.githubusercontent.com/ 이 URL을 사용해야 되는건가요??

https://github.com/eastroots92/TIL-Today_I_Learned/blob/master/Web/'X-FRAME-OPTIONS'%20to%20'SAMEORIGN'%20ISSUE.md 이러한 URL을 넣으면 어떻게 되는지 궁금합니다.

2018-05-17 02:57 UTC, eastroots92 commented on source/main.js
> +    areas.each(function(idx) {
이 부분도 Doc.ready에서 바로 function 선언 및 실행하는 것이 아니라 외부 function 또는 하단에 function으로 따로 만들고 여기서는 해당 function을 실행하는 정도로하면 보기 더 좋을 것 같은데 어떤가요?

2018-05-17 14:12 UTC, ciiwol commented on examples/sample.html
> +            url=" https://raw.githubusercontent.com/Porkstewdio/pork_your_markdown/master/README.md"></div>
오 이런거도되네 근데 커멘트는 왜 알림안왔지 내가 못봤나

해당 구현은 말 그대로 url로부터 raw text를 읽어와서 처리하는 부분이므로, github의 경우 raw textfile을 반환해주는 주소인 raw.githubusercontent.com를 써야합니다

2018-05-17 14:13 UTC, ciiwol commented on source/main.js
> +    areas.each(function(idx) {
추후에 테마 설정 기능이나 출력 옵션등을 설정할 것을 생각하면 제시해주신 방향이 더 좋아보입니다.

2018-05-17 14:14 UTC, ciiwol commented on source/main.js
> +    areas.each(function(idx) {
아 바꿔서 다시푸쉬하라고?

2018-05-17 14:21 UTC, jujinkim commented on examples/sample.html
> +            url=" https://raw.githubusercontent.com/Porkstewdio/pork_your_markdown/master/README.md"></div>
raw가 아닌 github repo 웹페이지 html로부터 파싱해서 뜯어오라면 뜯어올 순 있는데, 우선 파싱 전에 받아와야 할 html 데이터도 크고, 파싱하기도 귀찮고, 무엇보다 서비스중인 구조는 언제든 바뀔 수 있어서 향후 문제가 발생할 확률이 비교적 높습니다.

확실히 raw.githubusercontent.com은 일반 사용자가 바로 따오기 어려운 url이 맞습니다. 그래서 url 말고 직접 path로 접근할 수 있는 username/project/branch/path 등의 다른 경로를 뚫어놓았습니다.

2018-05-18 06:10 UTC, eastroots92 commented on examples/sample.html
> +            url=" https://raw.githubusercontent.com/Porkstewdio/pork_your_markdown/master/README.md"></div>
네 알겠습니다!!

2018-05-18 06:12 UTC, eastroots92 commented on source/main.js
> +    areas.each(function(idx) {
이부분은 바로 수정해서 올려도 좋고 아니면 일단 머지하고 추후 개발 방향을 확실히 한 다음에  다음번 구현에서 수정 후 올려도 좋을 듯 싶습니다.

2018-05-18 06:14 UTC, eastroots92 approved these changes

2018-05-18 06:18 UTC, merged

2018-05-20 07:30 UTC, eastroots92 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Markdown CSS 만들기](https://trello.com/c/8twdFBON/1-markdown-css-%EB%A7%8C%EB%93%A4%EA%B8%B0)