Use showdown as md2html tool. And check whether libraries are loaded or not before init.
Porkstewdio/pork_your_markdown pull request #5
Opened 2018-08-26 16:58 UTC by jujinkim

2018-08-26 17:02 UTC, jujinkim commented
처음에는 md2html 변환 js를 직접 구현하려고 했음. 그쪽이 튜닝도 쉽고 나중에 테마라던지 스타일링하기도 좋으니깐.
9aa1576 부터 e417b39까지의 커밋이 그 발악을 나타낸 커밋.

하지만 어느순간부터 만사가 귀찮고 바뻐져서 일단은 showdownJS를 사용하기로함.
941cc17 커밋은, 혼자 만들려고했던 md2html코드를 주석처리해버리고 showdownJS를 연동해서 변환하는 코드가 들어있다.

그리고 추가적으로, 사용자가 만약 페이지에 jquery나 showdown 스크립트를 넣지 않았다면, pumd initialize 전에 체크해서 저 스크립트들을 동적으로 넣고 init을 실행한다. (의존성은 그대로, 사용자 편의는 올라감)

2018-08-26 17:04 UTC, jujinkim commented
뭔 50줄도안되는 js코드 나부랭이가 빌드시작하는데 5분이넘게걸려

2018-08-27 02:49 UTC, eastroots92 requested changes

2018-08-27 02:49 UTC, eastroots92 commented on source/getMarkdown.js
> +        let converter = new Md2HtmlConverter(content);
var, let 보다 해당 함수 내에서 해당 값이 변경될 여지가 없다면 const 사용하는 것이 좋다고 생각합니다!

2018-08-27 02:49 UTC, eastroots92 commented on source/getMarkdown.js
> +        let html = converter.toHTML();
위와 같은 사유로 const 사용이 더 좋다고 생각하는데 어떻게 생각하세요?

2018-08-27 02:49 UTC, eastroots92 commented on source/main.js
> +    let jq = document.createElement('script');
제 개인적인 의견으로는 jq라는 것이 jQuery를 호출하기 위한 코드라는 것을 유추는 가능하나 보다 명확하게 `jquery`와 같은 네이밍을 적어주는 것이 좋다고 생각하는데 어떻게 생각하시나요??
위의 코드도 `let` 을 사용하기보다는 `const`를 사용하는 것이 좋아 보입니다.

`const`를 이용할 경우 본인이 의도하지 않은 값 변경을 막을 수 있고 다른사람들도 보다 명확하게 해당 변수들을 사용할 수 있어 특별한 이유가 아니라면 const 사용이 좋다고 생각합니다.

2018-08-27 03:44 UTC, jujinkim commented on source/main.js
> +    let jq = document.createElement('script');
ㅇㅈ합니다

2018-08-27 03:44 UTC, jujinkim commented on source/getMarkdown.js
> +        let html = converter.toHTML();
그게더좋겟습니다 근데 이거 수정하고 풀리퀘다시날리면 바뀌나

2018-08-27 03:58 UTC, eastroots92 commented on source/getMarkdown.js
> +        let html = converter.toHTML();
네 수정하고 다시 날리면 해당 기록은 덮어 씌워집니다.

2018-08-27 13:45 UTC, merged